name: solian
description: "The Solar Network App"
publish_to: "none"

version: 1.3.7+9

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^14.1.1
  get: ^4.6.6
  timeago: ^3.6.1
  flutter_markdown: ^0.7.1
  flutter_animate: ^4.5.0
  flutter_secure_storage: ^9.2.1
  url_launcher: ^6.2.6
  infinite_scroll_pagination: ^4.0.0
  image_picker: ^1.1.1
  file_picker: ^8.0.3
  crypto: ^3.0.3
  path: ^1.9.0
  intl: ^0.19.0
  font_awesome_flutter: ^10.7.0
  web_socket_channel: ^3.0.0
  permission_handler: ^11.3.1
  uuid: ^4.4.0
  dropdown_button2: ^2.3.9
  livekit_client: ^2.1.5
  flutter_webrtc: ^0.11.4
  wakelock_plus: ^1.2.5
  cached_network_image: ^3.3.1
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  package_info_plus: ^8.0.0
  device_info_plus: ^11.0.0
  flutter_acrylic: ^1.1.4
  protocol_handler: ^0.2.0
  markdown: ^7.2.2
  pasteboard: ^0.3.0
  desktop_drop: ^0.5.0
  badges: ^3.1.2
  flutter_card_swiper: ^7.0.1
  dismissible_page: ^1.0.2
  share_plus: ^10.0.0
  flutter_cache_manager: ^3.3.3
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  gal: ^2.3.0
  dio: ^5.5.0+1
  image_cropper: ^8.0.1
  markdown_toolbar: ^0.5.0
  animations: ^2.0.11
  avatar_stack: ^1.2.0
  async: ^2.11.0
  field_suggestion: ^0.2.5
  flutter_typeahead: ^5.2.0
  collection: ^1.18.0
  firebase_crashlytics: ^4.0.4
  firebase_analytics: ^11.2.1
  firebase_performance: ^0.10.0+4
  flutter_svg: ^2.0.10+1
  cross_file: ^0.3.4+2
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  gap: ^3.0.1
  fl_chart: ^0.69.0
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  drift: ^2.20.2
  drift_flutter: ^0.2.0
  very_good_infinite_list: ^0.8.0
  path_provider: ^2.1.4
  flutter_background_service: ^5.0.10
  flutter_local_notifications: ^17.2.2
  flutter_app_update: ^3.1.0
  version: ^3.0.2
  action_slider: ^0.7.0
  in_app_review: ^2.0.9
  syntax_highlight: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.0

  build_runner: ^2.4.12
  flutter_native_splash: ^2.4.1
  json_serializable: ^6.8.0
  drift_dev: ^2.20.3

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/locales/
    - assets/highlighting/

  fonts:
    - family: NotoSansEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.ttf
        - asset: assets/fonts/NotoSansSC-Bold.ttf
          weight: 700
    - family: NotoSansHK
      fonts:
        - asset: assets/fonts/NotoSansHK-Regular.ttf
        - asset: assets/fonts/NotoSansHK-Bold.ttf
          weight: 700
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.ttf
        - asset: assets/fonts/NotoSansJP-Bold.ttf
          weight: 700
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon-w-shadow.png"
    background_color: "#ffffff"
    theme_color: "#92645d"
  windows:
    generate: true
    image_path: "assets/icon-w-shadow.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/icon-w-shadow.png"

flutter_native_splash:
  color: "#fef8f7"
  color_dark: "#191110"
  image: assets/icon-w-shadow.png

msix_config:
  protocol_activation: solink
