name: solian
description: "The Solar Network App"
publish_to: "none"

version: 1.2.1+12

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.1.1
  get: ^4.6.6
  timeago: ^3.6.1
  flutter_markdown: ^0.7.1
  flutter_animate: ^4.5.0
  flutter_secure_storage: ^9.2.1
  carousel_slider: ^5.0.0
  url_launcher: ^6.2.6
  infinite_scroll_pagination: ^4.0.0
  image_picker: ^1.1.1
  file_picker: ^8.0.3
  crypto: ^3.0.3
  path: ^1.9.0
  intl: ^0.19.0
  font_awesome_flutter: ^10.7.0
  web_socket_channel: ^3.0.0
  permission_handler: ^11.3.1
  uuid: ^4.4.0
  dropdown_button2: ^2.3.9
  livekit_client: ^2.1.5
  flutter_webrtc: ^0.11.4
  wakelock_plus: ^1.2.5
  cached_network_image: ^3.3.1
  sentry_flutter: ^8.2.0
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0
  flutter_acrylic: ^1.1.4
  floor: ^1.5.0
  sqflite: ^2.3.3+1
  protocol_handler: ^0.2.0
  markdown: ^7.2.2
  media_kit: ^1.1.10+1
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  pasteboard: ^0.2.0
  desktop_drop: ^0.4.4
  badges: ^3.1.2
  flutter_card_swiper: ^7.0.1
  dismissible_page: ^1.0.2
  share_plus: ^10.0.0
  flutter_cache_manager: ^3.3.3
  flutter_markdown_selectionarea: ^0.6.17+1
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  gal: ^2.3.0
  dio: ^5.5.0+1
  image_cropper: ^8.0.1
  markdown_toolbar: ^0.5.0
  animations: ^2.0.11
  avatar_stack: ^1.2.0
  async: ^2.11.0
  field_suggestion: ^0.2.5
  flutter_typeahead: ^5.2.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

  floor_generator: ^1.4.0
  build_runner: ^2.1.2
  sqflite_common_ffi: ^2.3.3
  sqflite_common_ffi_web: ^0.4.3+1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

  fonts:
    - family: NotoSansEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.ttf
        - asset: assets/fonts/NotoSansSC-Bold.ttf
          weight: 700
    - family: NotoSansHK
      fonts:
        - asset: assets/fonts/NotoSansHK-Regular.ttf
        - asset: assets/fonts/NotoSansHK-Bold.ttf
          weight: 700
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.ttf
        - asset: assets/fonts/NotoSansJP-Bold.ttf
          weight: 700
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android:
    generate: "launcher_icon"
    image_path: "assets/icon.png"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon-w-shadow.png"
    background_color: "#ffffff"
    theme_color: "#4b5094"
  windows:
    generate: true
    image_path: "assets/icon-w-shadow.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/icon-w-shadow.png"

msix_config:
  protocol_activation: solink
