name: release-nightly

on:
  push:
    branches: [master]

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter build web
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output-web
          path: build/web
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
      - run: flutter pub get
      - run: flutter build apk --split-per-abi
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output-android
          path: build/app/outputs/flutter-apk/*.apk
  build-exe:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter build windows
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output-windows
          path: build/windows
